### ISSUE TITLE
Foundry Install Fail - No Valid manifest file.

### ISSUE THREAD

**Issue by Celstra** [ian612/sfrpgbb#32]
Installation failed: The request to https://raw.githubusercontent.com/ian612/sfrpgbb/main/system.js did not provide a valid manifest file.

![image](https://user-images.githubusercontent.com/5407684/187054340-65429048-1e83-4faf-92ae-a17c638e85eb.png)

**Comment by ian612** [comment]
The manifest file should have had a .json file extension, not .js
Issue has been corrected, and install should work, now
