### ISSUE TITLE
Missing lines in the localisation file

### ISSUE THREAD

**Issue by Vesselchuck** [ian612/sfrpgbb#37]
There are some missing lines for NPC Sheet:
![Screenshot_1](https://user-images.githubusercontent.com/70449411/190870905-39be5234-f271-4a4c-ac53-ee4f62e3d5af.png)
**Equipment**
![Screenshot_2](https://user-images.githubusercontent.com/70449411/190870908-0790e832-c57b-40b5-aeef-843950eddecb.png)
**Ranged and Melee attacks**

And PC Sheet:
![image](https://user-images.githubusercontent.com/70449411/190870978-a59690d0-400a-45ac-8b2b-bbe9ff9f580e.png)
**The very top of the sheet**
![image](https://user-images.githubusercontent.com/70449411/190871087-fa281325-de80-43ba-b7dd-8359f2e5f4f5.png)
**Spells**

Is it possible to add these lines to the localisation file so that a full translation of these Shets can be made?

**Comment by ian612** [comment]
These localization oversights have been fixed.
