### ISSUE TITLE
Second Diagonals

### ISSUE THREAD

**Issue by RunningRyan** [ian612/sfrpgbb#50]
For some reason my version (Foundry v10) wont calculate every second diagonal as 10ft rather than 5ft. There is no option in the "Configure Settings" to implement "second diagonal" rule.

**Comment by ian612** [comment]
Thanks for pointing this out, I had totally missed it. I'll add a fix and it'll be in the next release.

**Comment by ian612** [comment]
This is fixed in Release 1.3.0 for v11
